/**
 * @file RootLayout component for the application.
 * @module RootLayout
 * @description This component serves as the root layout for the application. It wraps all pages with a consistent layout,
 * including a header and a toast notification system. It also sets up global fonts and metadata for the application.
 * 
 * @param {Object} props - The props passed to the component.
 * @param {React.ReactNode} props.children - The child components to be rendered within the layout.
 * @returns {JSX.Element} The rendered RootLayout component.
 * 
 * @example
 * // Usage in a Next.js app
 * <RootLayout>
 *   <PageComponent />
 * </RootLayout>
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";

// Load Geist Sans and Geist Mono fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * @function RootLayout
 * @description The root layout component for the application. It wraps all pages with a consistent layout,
 * including a header and a toast notification system. It also sets up global fonts and metadata.
 * 
 * @param {Object} props - The props passed to the component.
 * @param {React.ReactNode} props.children - The child components to be rendered within the layout.
 * @returns {JSX.Element} The rendered RootLayout component.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header /> {/* Render the header component */}
        {children} {/* Render the child components */}
        <Toaster position="top-right" /> {/* Toast notification system */}
      </body>
    </html>
  );
}